= Complete Changelog

== Jakarta EE Example Applications

=== August 23, 2024

* Update `index.html` files for consistency

=== August 20, 2024

* Update Payara scripts to use Payara Micro 7.2024.1.Alpha1
* Improvements to the HelloWorld section of the Jakarta Servlet example application
* Update `index.html` file for the Jakarta Mail example application to the match all the other example applications

=== August 19, 2024

* Initial updates on specification document and individual `README.adoc` files
* Dependency upgrades
* Minor improvements to Jakarta Validation example application
* Add new `getMatchedResourceTemplate()  method, defined in the https://jakarta.ee/specifications/restful-ws/4.0/apidocs/jakarta.ws.rs/jakarta/ws/rs/core/uriinfo[`UriInfo`] interface
* Update Payara scripts to use the August 2024 release of Payara Micro 6.2024.8

=== June 30, 2024

* Update to Jakarta EE 11-M4 and test projects for proper operation

=== June 25, 2024

* Update Payara scripts to use the June 2024 release of Payara Micro 6.2024.6
* Update Jakarta Security to 4.0.0 from 4.0.0-M2 and test for proper operation
* Cleanup `pom.xml` file in the Jakarta RESTful Web Services example application

=== June 13, 2024

* Add a Java record in the Jakarta Validation example application to complement the POJO
* Update Jakarta EE specification dependencies as necessary relative to the latest versions


=== May 29, 2024

* Introduce the `CHANGELOG.adoc` file.
* Update the stylesheet on the Jakarta Concurrency demo to be consistent with the other example applications.
* Fix the duplicate `width="x"` `width="y"` to `width=x height="y"` referencing the Jakarta EE logo in the `index.html` files within each application.



