== Jakarta Validation Example Application

=== Introduction

The https://jakarta.ee/specifications/bean-validation/[Jakarta Validation] specification, currently at version 3.0, provides an object level constraint declaration and validation facility as well as a constraint metadata repository and query API.

It also offers method and constructor validation facilities to ensure constraints on their parameters and return values.

The compatible implementation for this specification is https://hibernate.org/validator/releases/7.0/[Hibernate Validator 8.0.0.Alpha5]

NOTE:: Jakarta Validation was formerly known as Jakarta Bean Validation.

Jakarta Validation will be updated to version 3.1 for Jakarta EE 11. New features include:

* support for Java Records

=== Example Application

The application may be exercised by running the CLI version or deployed on Payara Cloud:

`$ mvn clean compile exec:java`

* https://validation-demo-dev-695bb9e4.payara.app/validation/[Welcome Page]
* https://validation-demo-dev-695bb9e4.payara.app/validation/validation/validate[Main Application]

=== Testing

Please stay tuned for details...
