= Jakarta Data Demo Application

This project is a demonstration on how to use the Jakarta Data specification. The intent is to provide both command-line and REST applications. However, both versions may not be available at this time.

== Command-Line Application

There are three command-line applications: is currently a placeholder for a more comprehensive application.
The `BeerApp` beer database application uses a MongoDB NoSQL database  class is referenced in the `pom.xml` file as `<mainClass>org.redlich.concurrency.ConcurrencyApp</mainClass>`, so executing it is as easy as:

The `FakerBeerApp` beer database application uses a the Faker

`$ mvn clean compile exec:java`

Upon executing this application, you will be presented with the following output on the terminal window:

[APP] ---------------------------------------------------------
[APP] Welcome to the Jakarta Concurrency Demo Application
[APP] ---------------------------------------------------------

== REST Application

The REST application is a beer database that uses Jakarta Data, Jakarta NoSQL and MongoDB

`$ mvn clean compile package`

This will build a WAR file that may be dropped in any Jakarta EE-compliant application server.

== Executing the REST Application

`curl -X POST -H "Content-Type: application/json" -d '{"_id": 3, "name": "Russian Imperial Stout", "type": "STOUT", "brewer_id": 1, "abv": 10.2}' http://10.0.0.229:8080/beers/db/beer/3`

The REST application may be executed via:

http://10.0.0.229:8080/data-1.0.0/db[Main Application]
