== Jakarta Concurrency Example Application

=== Introduction

The https://jakarta.ee/specifications/concurrency/[Jakarta Concurrency] specification, currently at version 3.0, provides a mechanism for using concurrency from application components without compromising container integrity while still preserving the fundamental benefits of the Jakarta EE platform

The compatible implementation for this specification is https://openliberty.io/blog/2023/05/16/23.0.0.5-beta.html[Open Liberty 22.0.0.5-beta].

Jakarta Concurrency will be updated to version 3.1 for Jakarta EE 11. New features include:

* Integration with Java 21 Virtual Threads
* Java Flow/ReactiveStreams and context propagation
* Replace more features from EJB, such as Schedule and Lock annotations
* Become more CDI-centric
* Specification bug fixes and clarifications
* TCK fixes and enhancements

=== Example Application

The application may be exercised by running the CLI version or deployed on Payara Cloud:

`$ mvn clean compile exec:java`

* https://concurrency-demo-dev-bfa859d4.payara.app/concurrency/[Main Application]

=== Testing

Please stay tuned for details...
