== Jakarta Data

=== Introduction

The https://jakarta.ee/specifications/data/[Jakarta Data] specification, currently at version 1.0 for Jakarta EE 11, provides an API that allows easy access to database technologies. A Java developer can split the persistence from the model with several features, such as the ability to compose custom query methods on a `Repository` interface where the framework will implement it.

Jakarta Data, introduced in the summer of 2022, is a new specification for the Jakarta EE 11 Platform and Web Profile.

=== New Features

New features  in version 1.0 include:

* Support for CDI Extensions.
* A `BasicRepository` interface for performing basic operations on entities
* New annotations, `@Insert`, `@Update`, `@Delete` and `@Save`.
* A `CrudRepository` interface that extends the capabilities of basic operations on entities, including insert and update operations.
* A new https://jakarta.ee/specifications/data/1.0/jakarta-data-1.0#_jakarta_data_query_language[Jakarta Data Query Language] that complements the https://jakarta.ee/specifications/persistence/3.2/jakarta-persistence-spec-3.2#a4665[Jakarta Persistence Query Language] defined in the https://jakarta.ee/specifications/persistence/[Jakarta Persistence] specification.

=== Compatible Implementation(s)

The compatible implementations for this specification are https://github.com/hibernate/hibernate-orm/releases/tag/6.6.0.CR1[Hibernate ORM 6.6.0.Final] and https://github.com/OpenLiberty/open-liberty/releases/tag/gm-24.0.0.6[Open Liberty 24.0.0.6].
